### ISSUE TITLE
Hi! I have translated your mod into Russian!

### ISSUE THREAD

**Issue by AlpusFrostbite** [TerraFirmaCraftNetwork/HotOrNotTFC#4]
txt->lang
[ru_ru.txt](https://github.com/TerraFirmaCraftNetwork/HotOrNotTFC/files/13933333/ru_ru.txt)
That is all

**Comment by Lylythii** [comment]
Thank you! Merged that lang file into the mod. Should be available on CurseForge soon:
- [Hot or Not TFC - 1.12.2 - 1.2.1](https://curseforge.com/minecraft/mc-mods/hot-or-not-tfc/files/5182333)
